FROM nginx:stable-alpine-perl
LABEL maintainer="dummymail@gmail.com"
COPY confs/nginx.conf /etc/nginx/nginx.conf
COPY confs/http.conf /etc/nginx/conf.d/http.conf
COPY confs/default.conf /etc/nginx/conf.d/default.conf
